version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"      # AMQP port
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: quest     # Задайте ім'я користувача RabbitMQ
      RABBITMQ_DEFAULT_PASS: quest      # Задайте пароль RabbitMQ
    volumes:
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf  # Додаємо конфігураційний файл
